
// This file has been generated by the GUI designer. Do not modify.
namespace TdP2019TPFinalRichieri
{
	public partial class SessionResultDialog
	{
		private global::Gtk.VBox vboxSignUp;

		private global::Gtk.Image imgHeader;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label lblScore;

		private global::Gtk.Entry entryScore;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label lblTime;

		private global::Gtk.Entry entryTime;

		private global::Gtk.Button buttonClose;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TdP2019TPFinalRichieri.SessionResultDialog
			this.Name = "TdP2019TPFinalRichieri.SessionResultDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child TdP2019TPFinalRichieri.SessionResultDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vboxSignUp = new global::Gtk.VBox();
			this.vboxSignUp.Name = "vboxSignUp";
			this.vboxSignUp.Spacing = 6;
			// Container child vboxSignUp.Gtk.Box+BoxChild
			this.imgHeader = new global::Gtk.Image();
			this.imgHeader.Name = "imgHeader";
			this.imgHeader.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("TdP2019TPFinalRichieri.UI.Resources.Header.png");
			this.vboxSignUp.Add(this.imgHeader);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxSignUp[this.imgHeader]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxSignUp.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblScore = new global::Gtk.Label();
			this.lblScore.WidthRequest = 300;
			this.lblScore.Name = "lblScore";
			this.lblScore.LabelProp = global::Mono.Unix.Catalog.GetString("Score");
			this.hbox2.Add(this.lblScore);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lblScore]));
			w3.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entryScore = new global::Gtk.Entry();
			this.entryScore.WidthRequest = 200;
			this.entryScore.CanFocus = true;
			this.entryScore.Name = "entryScore";
			this.entryScore.IsEditable = false;
			this.entryScore.HasFrame = false;
			this.entryScore.InvisibleChar = '•';
			this.hbox2.Add(this.entryScore);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entryScore]));
			w4.Position = 1;
			this.vboxSignUp.Add(this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxSignUp[this.hbox2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxSignUp.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblTime = new global::Gtk.Label();
			this.lblTime.WidthRequest = 300;
			this.lblTime.Name = "lblTime";
			this.lblTime.LabelProp = global::Mono.Unix.Catalog.GetString("Time");
			this.hbox3.Add(this.lblTime);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblTime]));
			w6.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entryTime = new global::Gtk.Entry();
			this.entryTime.WidthRequest = 200;
			this.entryTime.CanFocus = true;
			this.entryTime.Name = "entryTime";
			this.entryTime.IsEditable = false;
			this.entryTime.HasFrame = false;
			this.entryTime.InvisibleChar = '•';
			this.hbox3.Add(this.entryTime);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entryTime]));
			w7.Position = 1;
			this.vboxSignUp.Add(this.hbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vboxSignUp[this.hbox3]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			w1.Add(this.vboxSignUp);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1[this.vboxSignUp]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Internal child TdP2019TPFinalRichieri.SessionResultDialog.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog1_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonClose = new global::Gtk.Button();
			this.buttonClose.CanDefault = true;
			this.buttonClose.CanFocus = true;
			this.buttonClose.Name = "buttonClose";
			this.buttonClose.UseStock = true;
			this.buttonClose.UseUnderline = true;
			this.buttonClose.Label = "gtk-close";
			this.AddActionWidget(this.buttonClose, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10[this.buttonClose]));
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 693;
			this.DefaultHeight = 300;
			this.Show();
			this.buttonClose.Clicked += new global::System.EventHandler(this.OnButtonCloseClicked);
		}
	}
}
