
// This file has been generated by the GUI designer. Do not modify.
namespace TdP2019TPFinalRichieri
{
	public partial class SessionDialog
	{
		private global::Gtk.VBox vboxSignUp;

		private global::Gtk.Image imgHeader;

		private global::Gtk.Entry entryQuestion;

		private global::Gtk.ComboBox cbbAnswers;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button btnClose;

		private global::Gtk.Button btnAnswer;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TdP2019TPFinalRichieri.SessionDialog
			this.Name = "TdP2019TPFinalRichieri.SessionDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child TdP2019TPFinalRichieri.SessionDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vboxSignUp = new global::Gtk.VBox();
			this.vboxSignUp.Name = "vboxSignUp";
			this.vboxSignUp.Spacing = 6;
			// Container child vboxSignUp.Gtk.Box+BoxChild
			this.imgHeader = new global::Gtk.Image();
			this.imgHeader.Name = "imgHeader";
			this.imgHeader.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("TdP2019TPFinalRichieri.UI.Resources.Header.png");
			this.vboxSignUp.Add(this.imgHeader);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxSignUp[this.imgHeader]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxSignUp.Gtk.Box+BoxChild
			this.entryQuestion = new global::Gtk.Entry();
			this.entryQuestion.CanFocus = true;
			this.entryQuestion.Name = "entryQuestion";
			this.entryQuestion.IsEditable = false;
			this.entryQuestion.InvisibleChar = '•';
			this.vboxSignUp.Add(this.entryQuestion);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxSignUp[this.entryQuestion]));
			w3.Position = 1;
			w3.Expand = false;
			// Container child vboxSignUp.Gtk.Box+BoxChild
			this.cbbAnswers = global::Gtk.ComboBox.NewText();
			this.cbbAnswers.WidthRequest = 200;
			this.cbbAnswers.Name = "cbbAnswers";
			this.vboxSignUp.Add(this.cbbAnswers);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vboxSignUp[this.cbbAnswers]));
			w4.Position = 2;
			w4.Expand = false;
			// Container child vboxSignUp.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.vboxSignUp.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxSignUp[this.hbox1]));
			w5.Position = 3;
			w1.Add(this.vboxSignUp);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1[this.vboxSignUp]));
			w6.Position = 0;
			// Internal child TdP2019TPFinalRichieri.SessionDialog.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "dialog1_ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnClose = new global::Gtk.Button();
			this.btnClose.CanDefault = true;
			this.btnClose.CanFocus = true;
			this.btnClose.Name = "btnClose";
			this.btnClose.UseUnderline = true;
			this.btnClose.Label = global::Mono.Unix.Catalog.GetString("_Close");
			this.AddActionWidget(this.btnClose, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7[this.btnClose]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnAnswer = new global::Gtk.Button();
			this.btnAnswer.CanDefault = true;
			this.btnAnswer.CanFocus = true;
			this.btnAnswer.Name = "btnAnswer";
			this.btnAnswer.UseUnderline = true;
			this.btnAnswer.Label = global::Mono.Unix.Catalog.GetString("_Answer");
			this.AddActionWidget(this.btnAnswer, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7[this.btnAnswer]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 693;
			this.DefaultHeight = 377;
			this.Show();
			this.btnClose.Clicked += new global::System.EventHandler(this.OnBtnCloseClicked);
			this.btnAnswer.Clicked += new global::System.EventHandler(this.OnBtnAnswerClicked);
		}
	}
}
