
// This file has been generated by the GUI designer. Do not modify.
namespace TdP2019TPFinalRichieri
{
	public partial class NewSessionDialog
	{
		private global::Gtk.VBox vboxSignUp;

		private global::Gtk.Image imgHeader;

		private global::Gtk.Frame frameNewSession;

		private global::Gtk.Alignment algSignUp;

		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hboxUsername;

		private global::Gtk.Label lblCategory;

		private global::Gtk.ComboBox cbbCategories;

		private global::Gtk.HBox hboxPassword;

		private global::Gtk.Label lblLevel;

		private global::Gtk.ComboBox cbbLevels;

		private global::Gtk.HBox hboxConfirmPassword;

		private global::Gtk.Label lblQuestionsQty;

		private global::Gtk.ComboBox cbbQuestionsNumber;

		private global::Gtk.Label lblNewSession;

		private global::Gtk.Button btnCancel;

		private global::Gtk.Button btnStart;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TdP2019TPFinalRichieri.NewSessionDialog
			this.Name = "TdP2019TPFinalRichieri.NewSessionDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child TdP2019TPFinalRichieri.NewSessionDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vboxSignUp = new global::Gtk.VBox();
			this.vboxSignUp.Name = "vboxSignUp";
			this.vboxSignUp.Spacing = 6;
			// Container child vboxSignUp.Gtk.Box+BoxChild
			this.imgHeader = new global::Gtk.Image();
			this.imgHeader.Name = "imgHeader";
			this.imgHeader.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("TdP2019TPFinalRichieri.UI.Resources.Header.png");
			this.vboxSignUp.Add(this.imgHeader);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxSignUp[this.imgHeader]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxSignUp.Gtk.Box+BoxChild
			this.frameNewSession = new global::Gtk.Frame();
			this.frameNewSession.Name = "frameNewSession";
			this.frameNewSession.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frameNewSession.Gtk.Container+ContainerChild
			this.algSignUp = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.algSignUp.HeightRequest = 200;
			this.algSignUp.Name = "algSignUp";
			this.algSignUp.LeftPadding = ((uint)(12));
			// Container child algSignUp.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hboxUsername = new global::Gtk.HBox();
			this.hboxUsername.Name = "hboxUsername";
			this.hboxUsername.Spacing = 6;
			// Container child hboxUsername.Gtk.Box+BoxChild
			this.lblCategory = new global::Gtk.Label();
			this.lblCategory.WidthRequest = 150;
			this.lblCategory.Name = "lblCategory";
			this.lblCategory.LabelProp = global::Mono.Unix.Catalog.GetString("Category");
			this.lblCategory.Justify = ((global::Gtk.Justification)(1));
			this.hboxUsername.Add(this.lblCategory);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxUsername[this.lblCategory]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hboxUsername.Gtk.Box+BoxChild
			this.cbbCategories = global::Gtk.ComboBox.NewText();
			this.cbbCategories.WidthRequest = 300;
			this.cbbCategories.Name = "cbbCategories";
			this.hboxUsername.Add(this.cbbCategories);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxUsername[this.cbbCategories]));
			w4.Position = 1;
			w4.Expand = false;
			this.vbox2.Add(this.hboxUsername);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hboxUsername]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hboxPassword = new global::Gtk.HBox();
			this.hboxPassword.Name = "hboxPassword";
			this.hboxPassword.Spacing = 6;
			// Container child hboxPassword.Gtk.Box+BoxChild
			this.lblLevel = new global::Gtk.Label();
			this.lblLevel.WidthRequest = 150;
			this.lblLevel.Name = "lblLevel";
			this.lblLevel.LabelProp = global::Mono.Unix.Catalog.GetString("Level");
			this.lblLevel.Justify = ((global::Gtk.Justification)(1));
			this.hboxPassword.Add(this.lblLevel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxPassword[this.lblLevel]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hboxPassword.Gtk.Box+BoxChild
			this.cbbLevels = global::Gtk.ComboBox.NewText();
			this.cbbLevels.WidthRequest = 300;
			this.cbbLevels.Name = "cbbLevels";
			this.hboxPassword.Add(this.cbbLevels);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxPassword[this.cbbLevels]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add(this.hboxPassword);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hboxPassword]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hboxConfirmPassword = new global::Gtk.HBox();
			this.hboxConfirmPassword.Name = "hboxConfirmPassword";
			this.hboxConfirmPassword.Spacing = 6;
			// Container child hboxConfirmPassword.Gtk.Box+BoxChild
			this.lblQuestionsQty = new global::Gtk.Label();
			this.lblQuestionsQty.WidthRequest = 150;
			this.lblQuestionsQty.Name = "lblQuestionsQty";
			this.lblQuestionsQty.LabelProp = global::Mono.Unix.Catalog.GetString("Questions number");
			this.lblQuestionsQty.Justify = ((global::Gtk.Justification)(1));
			this.hboxConfirmPassword.Add(this.lblQuestionsQty);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxConfirmPassword[this.lblQuestionsQty]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hboxConfirmPassword.Gtk.Box+BoxChild
			this.cbbQuestionsNumber = global::Gtk.ComboBox.NewText();
			this.cbbQuestionsNumber.WidthRequest = 300;
			this.cbbQuestionsNumber.Name = "cbbQuestionsNumber";
			this.hboxConfirmPassword.Add(this.cbbQuestionsNumber);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxConfirmPassword[this.cbbQuestionsNumber]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox2.Add(this.hboxConfirmPassword);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hboxConfirmPassword]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.algSignUp.Add(this.vbox2);
			this.frameNewSession.Add(this.algSignUp);
			this.lblNewSession = new global::Gtk.Label();
			this.lblNewSession.Name = "lblNewSession";
			this.lblNewSession.LabelProp = global::Mono.Unix.Catalog.GetString("<b>New Session</b>");
			this.lblNewSession.UseMarkup = true;
			this.frameNewSession.LabelWidget = this.lblNewSession;
			this.vboxSignUp.Add(this.frameNewSession);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxSignUp[this.frameNewSession]));
			w14.Position = 1;
			w1.Add(this.vboxSignUp);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(w1[this.vboxSignUp]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Internal child TdP2019TPFinalRichieri.NewSessionDialog.ActionArea
			global::Gtk.HButtonBox w16 = this.ActionArea;
			w16.Name = "dialog1_ActionArea";
			w16.Spacing = 10;
			w16.BorderWidth = ((uint)(5));
			w16.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnCancel = new global::Gtk.Button();
			this.btnCancel.CanDefault = true;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseStock = true;
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.btnCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w16[this.btnCancel]));
			w17.Expand = false;
			w17.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnStart = new global::Gtk.Button();
			this.btnStart.CanDefault = true;
			this.btnStart.CanFocus = true;
			this.btnStart.Name = "btnStart";
			this.btnStart.UseUnderline = true;
			this.btnStart.Label = global::Mono.Unix.Catalog.GetString("_Start");
			this.AddActionWidget(this.btnStart, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w16[this.btnStart]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 693;
			this.DefaultHeight = 377;
			this.Show();
			this.btnCancel.Clicked += new global::System.EventHandler(this.OnBtnCancelClicked);
			this.btnStart.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
