
// This file has been generated by the GUI designer. Do not modify.
namespace TdP2019TPFinalRichieri
{
	public partial class LogInDialog
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.Image imgHeader;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label lblUsername;

		private global::Gtk.Entry entUsername;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label lblPassword;

		private global::Gtk.Entry entPassword;

		private global::Gtk.Button btnSignUp;

		private global::Gtk.Button btnLogIn;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TdP2019TPFinalRichieri.LogInDialog
			this.Name = "TdP2019TPFinalRichieri.LogInDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("TriviaApp");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child TdP2019TPFinalRichieri.LogInDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.imgHeader = new global::Gtk.Image();
			this.imgHeader.Name = "imgHeader";
			this.imgHeader.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("TdP2019TPFinalRichieri.UI.Resources.Header.png");
			this.vbox6.Add(this.imgHeader);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.imgHeader]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblUsername = new global::Gtk.Label();
			this.lblUsername.WidthRequest = 100;
			this.lblUsername.Name = "lblUsername";
			this.lblUsername.LabelProp = global::Mono.Unix.Catalog.GetString("Username");
			this.lblUsername.Justify = ((global::Gtk.Justification)(1));
			this.hbox3.Add(this.lblUsername);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lblUsername]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entUsername = new global::Gtk.Entry();
			this.entUsername.CanFocus = true;
			this.entUsername.Name = "entUsername";
			this.entUsername.IsEditable = true;
			this.entUsername.InvisibleChar = '•';
			this.hbox3.Add(this.entUsername);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entUsername]));
			w4.Position = 1;
			this.vbox6.Add(this.hbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblPassword = new global::Gtk.Label();
			this.lblPassword.WidthRequest = 100;
			this.lblPassword.Name = "lblPassword";
			this.lblPassword.LabelProp = global::Mono.Unix.Catalog.GetString("Password");
			this.lblPassword.Justify = ((global::Gtk.Justification)(1));
			this.hbox4.Add(this.lblPassword);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblPassword]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entPassword = new global::Gtk.Entry();
			this.entPassword.CanFocus = true;
			this.entPassword.Name = "entPassword";
			this.entPassword.IsEditable = true;
			this.entPassword.InvisibleChar = '•';
			this.hbox4.Add(this.entPassword);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.entPassword]));
			w7.Position = 1;
			this.vbox6.Add(this.hbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox4]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			w1.Add(this.vbox6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1[this.vbox6]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Internal child TdP2019TPFinalRichieri.LogInDialog.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog1_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnSignUp = new global::Gtk.Button();
			this.btnSignUp.CanDefault = true;
			this.btnSignUp.CanFocus = true;
			this.btnSignUp.Name = "btnSignUp";
			this.btnSignUp.UseUnderline = true;
			this.btnSignUp.Label = global::Mono.Unix.Catalog.GetString("_Sign Up");
			w10.Add(this.btnSignUp);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10[this.btnSignUp]));
			w11.Expand = false;
			w11.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnLogIn = new global::Gtk.Button();
			this.btnLogIn.CanDefault = true;
			this.btnLogIn.CanFocus = true;
			this.btnLogIn.Name = "btnLogIn";
			this.btnLogIn.UseUnderline = true;
			this.btnLogIn.Label = global::Mono.Unix.Catalog.GetString("_Log In");
			this.AddActionWidget(this.btnLogIn, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10[this.btnLogIn]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 693;
			this.DefaultHeight = 300;
			this.Show();
			this.btnSignUp.Clicked += new global::System.EventHandler(this.OnClickBtnSignUp);
			this.btnLogIn.Clicked += new global::System.EventHandler(this.OnClickLogIn);
		}
	}
}
