
// This file has been generated by the GUI designer. Do not modify.
namespace TdP2019TPFinalRichieri
{
	public partial class SettingsDialog
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Image imgHeader;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label lblQuestionSetName;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label lblExpectedAnswerTime;

		private global::Gtk.Entry entExpectedAnswerTime;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button btnUpdateData;

		private global::Gtk.Label lblLoading;

		private global::Gtk.Label lblSettings;

		private global::Gtk.Button btnBack;

		private global::Gtk.Button btnSave;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TdP2019TPFinalRichieri.SettingsDialog
			this.Name = "TdP2019TPFinalRichieri.SettingsDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("Settings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 640;
			this.DefaultHeight = 480;
			// Internal child TdP2019TPFinalRichieri.SettingsDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.imgHeader = new global::Gtk.Image();
			this.imgHeader.Name = "imgHeader";
			this.imgHeader.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("TdP2019TPFinalRichieri.UI.Resources.Header.png");
			this.vbox2.Add(this.imgHeader);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.imgHeader]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblQuestionSetName = new global::Gtk.Label();
			this.lblQuestionSetName.Name = "lblQuestionSetName";
			this.lblQuestionSetName.LabelProp = global::Mono.Unix.Catalog.GetString("<b>lblQuestionSetName</b>");
			this.lblQuestionSetName.UseMarkup = true;
			this.vbox3.Add(this.lblQuestionSetName);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.lblQuestionSetName]));
			w3.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblExpectedAnswerTime = new global::Gtk.Label();
			this.lblExpectedAnswerTime.Name = "lblExpectedAnswerTime";
			this.lblExpectedAnswerTime.LabelProp = global::Mono.Unix.Catalog.GetString("Expected Answer Time:");
			this.lblExpectedAnswerTime.UseMarkup = true;
			this.lblExpectedAnswerTime.Justify = ((global::Gtk.Justification)(1));
			this.lblExpectedAnswerTime.Angle = 3.46944695195361E-18D;
			this.hbox1.Add(this.lblExpectedAnswerTime);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblExpectedAnswerTime]));
			w4.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entExpectedAnswerTime = new global::Gtk.Entry();
			this.entExpectedAnswerTime.CanFocus = true;
			this.entExpectedAnswerTime.Name = "entExpectedAnswerTime";
			this.entExpectedAnswerTime.IsEditable = true;
			this.entExpectedAnswerTime.InvisibleChar = '•';
			this.hbox1.Add(this.entExpectedAnswerTime);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entExpectedAnswerTime]));
			w5.Position = 1;
			this.vbox3.Add(this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnUpdateData = new global::Gtk.Button();
			this.btnUpdateData.WidthRequest = 260;
			this.btnUpdateData.CanFocus = true;
			this.btnUpdateData.Name = "btnUpdateData";
			this.btnUpdateData.UseUnderline = true;
			this.btnUpdateData.Label = global::Mono.Unix.Catalog.GetString("Update Data");
			this.hbox2.Add(this.btnUpdateData);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnUpdateData]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblLoading = new global::Gtk.Label();
			this.lblLoading.Name = "lblLoading";
			this.lblLoading.LabelProp = global::Mono.Unix.Catalog.GetString("Loading...");
			this.hbox2.Add(this.lblLoading);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lblLoading]));
			w8.Position = 2;
			this.vbox3.Add(this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.GtkAlignment1.Add(this.vbox3);
			this.frame1.Add(this.GtkAlignment1);
			this.lblSettings = new global::Gtk.Label();
			this.lblSettings.Name = "lblSettings";
			this.lblSettings.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Settings</b>");
			this.lblSettings.UseMarkup = true;
			this.frame1.LabelWidget = this.lblSettings;
			this.vbox2.Add(this.frame1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			w1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Internal child TdP2019TPFinalRichieri.SettingsDialog.ActionArea
			global::Gtk.HButtonBox w14 = this.ActionArea;
			w14.Name = "dialog1_ActionArea";
			w14.Spacing = 10;
			w14.BorderWidth = ((uint)(5));
			w14.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnBack = new global::Gtk.Button();
			this.btnBack.CanDefault = true;
			this.btnBack.CanFocus = true;
			this.btnBack.Name = "btnBack";
			this.btnBack.UseUnderline = true;
			this.btnBack.Label = global::Mono.Unix.Catalog.GetString("_Back");
			this.AddActionWidget(this.btnBack, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14[this.btnBack]));
			w15.Expand = false;
			w15.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnSave = new global::Gtk.Button();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString("Save");
			this.AddActionWidget(this.btnSave, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w14[this.btnSave]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.lblLoading.Hide();
			this.Show();
			this.entExpectedAnswerTime.Changed += new global::System.EventHandler(this.OnEntExpectedAnswerTimeChanged);
			this.btnUpdateData.Clicked += new global::System.EventHandler(this.OnBtnUpdateDataClicked);
			this.btnBack.Clicked += new global::System.EventHandler(this.OnBtnBackClicked);
			this.btnSave.Clicked += new global::System.EventHandler(this.OnBtnSaveClicked);
		}
	}
}
